### PR TITLE
Bugfix/TG-2869 check if 'name' column exists

### PR DESCRIPTION
**Pull request by Axel-Girard**
Important changes are in the range of 2283 to 2289, remaining code is whitespaces

### CODE REVIEW

**Comment by ychab** [comment]
aouch, sounds like an evol for us... no? I mean, we could create a model without name in openerp??

**Comment by JoPotpot** [comment]
That's it. It is already the case, for openresa.booking.prestation, for example. That's why it crashed.
So we could had a 'name' column in this table, or just do this fix ? 
We thought it was better this way.

**Comment by ychab** [comment]
Ok and why not just overriding this method into the code of the class `openresa.booking.prestation` for the moment? We already have a lot of override in custom models (obvisouly 15, but not for the same reason)...

We are doing this in order to have a default behavior, like some other methods like https://github.com/opengst/odoo/blob/6.1-fix/openerp/osv/orm.py#L1870 ?

After all why not, it looks pretty safe.
Just a warning about less we touch the code of openerp, less we have to maintains it ;-)

**Comment by Axel-Girard** [comment]
Indeed, it can be done in the OpenresaBookingPrestation class, where the problem is.
Thx, I'm closing this branch (+ merge request) and I'll commit on opengst repository.

**Pull request closed without merging**
